###
GET http://localhost:8000


###
GET http://localhost:8000/test?user=subhadip


###
GET http://localhost:8000/test2/subhadip


###
POST http://localhost:8000/test3
Content-Type: application/json

{
    "name" : "Subahdip",
    "age": 30
}